<a href="https://colab.research.google.com/github/abhiram274/MachineLearning_concepts/blob/main/Vectorization_Onehot_and_LabelEncoders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import numpy as np

In [3]:
user_input = input("Enter categories separated by comma (e.g., Red,Blue,Green,Red): ")
categories = [x.strip() for x in user_input.split(',')]

Enter categories separated by comma (e.g., Red,Blue,Green,Red): red, green, blue,yellow,pink,brown,green,yellow


In [4]:
print("\nOriginal Categories:", categories)


Original Categories: ['red', 'green', 'blue', 'yellow', 'pink', 'brown', 'green', 'yellow']


In [16]:
# -------------------------------
# 2. Label Encoding
# -------------------------------
le = LabelEncoder()
label_encoded = le.fit_transform(categories)

print("\n=== Label Encoded Data ===")
print("Classes:", le.classes_)
print("Label Encoded:", label_encoded)


=== Label Encoded Data ===
Classes: ['blue' 'brown' 'green' 'pink' 'red' 'yellow']
Label Encoded: [4 2 0 5 3 1 2 5]


In [19]:
categories_array = np.array(categories).reshape(-1, 1)

ohe = OneHotEncoder(sparse_output=False)  # use sparse_output instead of sparse
one_hot_encoded = ohe.fit_transform(categories_array)

print("\n=== One-Hot Encoded Data ===")
print("Categories:", categories)
print(one_hot_encoded)


=== One-Hot Encoded Data ===
Categories: ['red', 'green', 'blue', 'yellow', 'pink', 'brown', 'green', 'yellow']
[[0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
